server {
    listen 80;
    server_name corposant.co.in www.corposant.co.in;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name corposant.co.in www.corposant.co.in;

    ssl_certificate /etc/letsencrypt/live/corposant.co.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/corposant.co.in/privkey.pem;

    # Frontend (React App)
    location / {
	proxy_pass http://frontend:80;
    }

    # Backend API
    location /api/ {
	proxy_pass http://backend:5000/;
    }
}
